language: cpp

compiler:
  - gcc
  - clang

branches:
 only:
  - master

# Init and update submodule
before_install:
  - git submodule update --init --recursive

# Make sure CMake is installed
install:
 - sudo apt-get update
 - sudo apt-get install cmake
 - mkdir build
 - cd build

script:
 - cmake -DSTRICT_MODE=ON .. && make && tests/tests